# main consts
SCREEN_WIDTH = 880
SCREEN_HEIGHT = 480
RES = (SCREEN_WIDTH, SCREEN_HEIGHT)
FPS = 60
GAME_TITLE = "Beware the night"
TILE_SIZE = (16, 16)
INGAME_TILE_SIZE = (80, 80)

# texts
FONT = "assets/Pixel.ttf"
START_SCREEN_TEXT = "Press Space to start"
START_SCREEN_TEXT_SIZE = 32
START_SCREEN_TEXT_POSITION = (SCREEN_WIDTH//2, SCREEN_HEIGHT//2)
SCORE_TEXT_SIZE = 28
SCORE_TEXT_POSITION = (SCREEN_WIDTH - 20, 20)
END_SCREEN_TEXT_POSITION = (SCREEN_WIDTH//2, SCREEN_HEIGHT//2)

# player
PLAYER_POSITION = (80, 400)

# enemies
ENEMY_POSITION_Y = 400
ENEMY_POSITION_X_1 = SCREEN_WIDTH + 500
ENEMY_POSITION_X_2 = SCREEN_WIDTH + 900

# colors
COLOR_LIGHT = "#e0f8d0"
COLOR_MID = "#88c070"
COLOR_DARK = "#346856"
COLOR_BLACK = "#081820"
COLOR_TRANSPARENT = "#66ff00"

# sprites
backgrounds = "assets/backgrounds2.png"
sprite_sheet = "assets/gameboy_platformer_texture_closer.png"
